/* Multi-step word problems, straight from the printed sets:
   Level 1 (2 steps), Level 2 (2-3 steps, harder numbers), Tricky Mode (traps),
   plus the Kumon-style unscaffolded set. */

export const WORD_SETS = {
  l1: {
    label: 'Mystery Lab: Level 1',
    blurb: 'Two steps. Read one line at a time. Step 1 feeds Step 2.',
    items: [
      { id: 'l1-1', title: "Dash's Rings", hero: 'speedster', unit: 'rings',
        lines: ['Dash collects 15 rings.', 'Then he collects 12 more rings.', 'The egg-shaped villain steals 8 of his rings.'],
        question: 'How many rings does Dash have now?',
        steps: [ { label: 'Add the rings he collected', answer: 27 }, { label: 'Subtract the stolen rings', answer: 19 } ] },
      { id: 'l1-2', title: "Blocky's Blocks", hero: 'miner', unit: 'blocks',
        lines: ['Blocky mines 30 blocks of stone.', 'He uses 12 blocks to build a wall.', 'Then he finds 6 more blocks.'],
        question: 'How many blocks does Blocky have now?',
        steps: [ { label: 'Subtract the blocks he used', answer: 18 }, { label: 'Add the blocks he found', answer: 24 } ] },
      { id: 'l1-3', title: "Web's Web-Swings", hero: 'webhero', unit: 'windows',
        lines: ['Web swings past 6 buildings.', 'Each building has 3 windows.', 'He also checks 5 windows on the ground.'],
        question: 'How many windows did he check in all?',
        steps: [ { label: 'Multiply buildings x windows', answer: 18 }, { label: 'Add the ground windows', answer: 23 } ] },
      { id: 'l1-4', title: "Volt's Team", hero: 'sparkmouse', unit: 'creatures',
        lines: ['A trainer catches 8 creatures in the morning.', 'He catches 7 more in the afternoon.', 'He trades away 5 of them.'],
        question: 'How many does the trainer have now?',
        steps: [ { label: 'Add the ones he caught', answer: 15 }, { label: 'Subtract the traded ones', answer: 10 } ] },
      { id: 'l1-5', title: 'Sidekick Laps', hero: 'speedster', unit: 'laps',
        lines: ['The two-tailed sidekick runs 24 laps on Monday.', 'He runs 9 fewer laps on Tuesday than Monday.'],
        question: 'How many laps did he run on both days combined?',
        steps: [ { label: "Find Tuesday's laps (subtract)", answer: 15 }, { label: 'Add Monday + Tuesday', answer: 39 } ] },
      { id: 'l1-6', title: 'Diamond Rows', hero: 'miner', unit: 'blocks',
        lines: ['A miner has 5 rows of diamond blocks.', 'Each row has 4 blocks.', 'She sells 8 blocks at the market.'],
        question: 'How many diamond blocks does she have left?',
        steps: [ { label: 'Multiply rows x blocks', answer: 20 }, { label: 'Subtract the blocks she sold', answer: 12 } ] },
      { id: 'l1-7', title: 'Photo Cleanup', hero: 'webhero', unit: 'photos',
        lines: ['A reporter takes 45 photos of the goblin.', 'He deletes 17 blurry photos.', 'Then he takes 9 more good photos.'],
        question: 'How many photos does he have now?',
        steps: [ { label: 'Subtract the blurry photos', answer: 28 }, { label: 'Add the new photos', answer: 37 } ] },
      { id: 'l1-8', title: "Trainer's Teams", hero: 'sparkmouse', unit: 'creatures',
        lines: ['A trainer has 3 teams.', 'Each team has 6 creatures.', 'He sends 2 of them to the storage box.'],
        question: 'How many does the trainer have with him now?',
        steps: [ { label: 'Multiply teams x creatures', answer: 18 }, { label: 'Subtract the ones sent away', answer: 16 } ] }
    ]
  },

  l2: {
    label: 'Mystery Lab: Level 2',
    blurb: 'Harder numbers. Some need THREE steps. Take your time.',
    items: [
      { id: 'l2-1', title: 'Zone Run', hero: 'speedster', unit: 'rings',
        lines: ['Dash runs through 6 zones.', 'Each zone has 8 rings hidden in it.', 'Dash already had 14 rings before he started.', 'The villain steals 20 rings from him.'],
        question: 'How many rings does Dash have now?',
        steps: [ { label: 'Multiply zones x rings', answer: 48 }, { label: 'Add his starting rings', answer: 62 }, { label: 'Subtract the stolen rings', answer: 42 } ] },
      { id: 'l2-2', title: 'Wall Project', hero: 'miner', unit: 'blocks',
        lines: ['Blocky wants to build 4 walls.', 'Each wall needs 15 blocks.', 'Blocky already has 25 blocks saved up.'],
        question: 'How many MORE blocks does Blocky need to find?',
        steps: [ { label: 'Multiply walls x blocks needed', answer: 60 }, { label: 'Subtract the blocks he already has', answer: 35 } ] },
      { id: 'l2-3', title: 'Photo Money', hero: 'webhero', unit: 'dollars',
        lines: ['A reporter sells photos of 7 villains to the newspaper.', 'Each photo sells for 6 dollars.', 'He already had 18 dollars saved.'],
        question: 'How much money does he have now?',
        steps: [ { label: 'Multiply photos x price', answer: 42 }, { label: 'Add his savings', answer: 60 } ] },
      { id: 'l2-4', title: 'Big Day', hero: 'sparkmouse', unit: 'creatures',
        lines: ['A trainer has 4 teams.', 'Each team has 6 creatures.', 'He releases 9 back into the wild.', 'Then he catches 11 new ones.'],
        question: 'How many does he have now?',
        steps: [ { label: 'Multiply teams x creatures', answer: 24 }, { label: 'Subtract the released ones', answer: 15 }, { label: 'Add the new catches', answer: 26 } ] },
      { id: 'l2-5', title: 'Ring Rate', hero: 'speedster', unit: 'rings',
        lines: ['The sidekick collects 45 rings over 3 days.', 'He collects the same number each day.', 'On day 4 he collects DOUBLE what he got on one normal day.'],
        question: 'How many rings does he have after all 4 days?',
        steps: [ { label: 'Divide to find rings per day', answer: 15 }, { label: 'Double that for day 4', answer: 30 }, { label: 'Add day 4 to the first 45', answer: 75 } ] },
      { id: 'l2-6', title: 'Chests', hero: 'miner', unit: 'per chest',
        lines: ['A miner has 72 diamond blocks.', 'She puts them equally into 8 chests.', 'Then she takes 3 blocks out of EACH chest to make tools.'],
        question: 'How many blocks are left in each chest?',
        steps: [ { label: 'Divide blocks / chests', answer: 9 }, { label: 'Subtract the blocks she took out', answer: 6 } ] },
      { id: 'l2-7', title: 'Swing Distance', hero: 'webhero', unit: 'miles',
        lines: ['Web swings 5 miles every day.', 'He does this for 6 days in a row.', 'On a special 7th day he swings 10 extra miles.'],
        question: 'How many total miles did he swing?',
        steps: [ { label: 'Multiply miles x days', answer: 30 }, { label: 'Add the extra miles', answer: 40 } ] },
      { id: 'l2-8', title: 'Shopping Trip', hero: 'sparkmouse', unit: 'balls',
        lines: ['A trainer already has 9 capture balls.', 'He buys 7 packs of balls.', 'Each pack has 6 balls in it.', 'He uses 15 balls that day.'],
        question: 'How many balls does he have left?',
        steps: [ { label: 'Multiply packs x balls per pack', answer: 42 }, { label: 'Add the balls he already had', answer: 51 }, { label: 'Subtract the balls he used', answer: 36 } ] }
    ]
  },

  tricky: {
    label: 'Mystery Lab: Tricky Mode',
    blurb: 'TRAPS AHEAD. Some numbers are useless. Watch for NOT and except.',
    items: [
      { id: 'tr-1', title: "Dash's Rings", hero: 'speedster', unit: 'rings', trap: 'EXTRA INFO',
        lines: ['Dash collects 20 rings in Zone 1.', 'The sidekick has a blue tail and can fly.', 'Dash collects 15 more rings in Zone 2.', 'He loses 12 rings to spikes.'],
        question: 'How many rings does Dash have now?',
        trapNote: 'The blue tail sentence has no number you need. Cross it out.',
        steps: [ { label: 'Add the rings he collected', answer: 35 }, { label: 'Subtract the rings he lost', answer: 23 } ] },
      { id: 'tr-2', title: 'Leftover Blocks', hero: 'miner', unit: 'blocks', trap: 'NOT QUESTION',
        lines: ['Blocky mines 18 stone blocks and 12 dirt blocks.', 'He uses 20 blocks to build a house.'],
        question: 'How many blocks did Blocky NOT use for the house?',
        trapNote: 'NOT used means what is LEFT OVER. Add everything first.',
        steps: [ { label: 'Add ALL his blocks together', answer: 30 }, { label: 'Subtract the ones he used', answer: 10 } ] },
      { id: 'tr-3', title: 'Rescues', hero: 'webhero', unit: 'places', trap: 'EXCEPT',
        lines: ['Web saves people from 4 burning buildings.', 'He also saves people from 3 flooding streets.', 'He does NOT save anyone from 2 libraries, because the libraries were already empty.'],
        question: 'How many places did Web actually save people at?',
        trapNote: 'The 2 libraries do not count. Only add the real rescues.',
        steps: [ { label: 'Add only the places where he saved people', answer: 7 } ] },
      { id: 'tr-4', title: 'Catch Comparison', hero: 'sparkmouse', unit: 'more creatures', trap: 'TRICKY NUMBER',
        lines: ['A trainer catches 14 creatures on Route 1.', 'His rival catches 9 creatures on Route 2.', 'His little sister has 5 stuffed toys at home.'],
        question: 'How many MORE did the trainer catch than his rival?',
        trapNote: 'Stuffed toys are not caught creatures. Ignore the 5.',
        steps: [ { label: "Subtract rival's catch from the trainer's catch", answer: 5 } ] },
      { id: 'tr-5', title: 'Zones Skipped', hero: 'speedster', unit: 'rings', trap: 'EXCEPT',
        lines: ['Dash needs to visit 5 zones today.', 'He skips the Chemical Plant Zone because it is under construction.', 'In every zone he DOES visit, he collects 16 rings.'],
        question: 'How many rings does Dash collect today?',
        trapNote: 'He only visits 4 zones, not 5.',
        steps: [ { label: 'Find how many zones he actually visits', answer: 4 }, { label: 'Multiply zones visited x rings per zone', answer: 64 } ] },
      { id: 'tr-6', title: 'Enough Blocks?', hero: 'miner', unit: 'more blocks', trap: 'NOT ENOUGH?',
        lines: ['A miner needs 50 blocks to build a castle.', 'She has 18 oak blocks and 24 stone blocks.'],
        question: 'Does she have enough? If NOT, how many MORE does she need?',
        trapNote: 'Add what she has, then find the gap up to 50.',
        steps: [ { label: 'Add the blocks she already has', answer: 42 }, { label: "Subtract that from 50 to find what's missing", answer: 8 } ] },
      { id: 'tr-7', title: 'The Shortcut', hero: 'webhero', unit: 'blocks', trap: 'EXTRA INFO',
        lines: ['The hideout is 8 blocks away from Web.', 'Web takes a shortcut that is 3 blocks shorter than that.', 'Meanwhile the goblin flies 15 blocks away in a totally different direction.'],
        question: 'How many blocks does Web actually swing to reach the hideout?',
        trapNote: 'The goblin flying 15 blocks has nothing to do with the question.',
        steps: [ { label: 'Subtract the shortcut from the normal distance', answer: 5 } ] },
      { id: 'tr-8', title: 'The Mystery Type', hero: 'sparkmouse', unit: 'creatures', trap: 'NOT QUESTION',
        lines: ['A trainer has 12 creatures on his team in total.', '3 of them are Fire type.', '5 of them are Water type.', '2 of them are Grass type.', 'The rest are Electric type.'],
        question: 'How many are NOT Fire, Water, or Grass?',
        trapNote: 'Add the three named types, then subtract from the total.',
        steps: [ { label: 'Add Fire + Water + Grass', answer: 10 }, { label: 'Subtract that from the total team', answer: 2 } ] }
    ]
  },

  kumon: {
    label: 'Mystery Lab: Speed Set',
    blurb: 'No step boxes this time. Read it, solve it, type it.',
    items: [
      { id: 'ku-1', title: 'Race Wins', hero: 'speedster', unit: 'more times',
        lines: ['Dash and the sidekick raced through Green Hill Zone.', 'Dash finished first 12 times, and the sidekick finished first 5 times.'],
        question: 'How many more times did Dash finish first than the sidekick?',
        steps: [ { label: 'Solve it', answer: 7 } ] },
      { id: 'ku-2', title: 'Wood Chest', hero: 'miner', unit: 'blocks',
        lines: ["Blocky's chest had 84 blocks of wood.", 'He used 39 blocks to build a bridge.'],
        question: 'How many blocks of wood does Blocky have remaining?',
        steps: [ { label: 'Solve it', answer: 45 } ] },
      { id: 'ku-3', title: 'Two Web-Lines', hero: 'webhero', unit: 'centimeters',
        lines: ['Web built two web-lines across the city.', 'One was 3 meters 45 centimeters long.', 'The other was 1 meter 80 centimeters long.', 'Remember: 1 meter = 100 centimeters.'],
        question: 'What is the difference in length, in centimeters?',
        steps: [ { label: 'Solve it (turn meters into centimeters first)', answer: 165 } ] },
      { id: 'ku-4', title: 'Missing Balls', hero: 'sparkmouse', unit: 'balls',
        lines: ['There were 28 capture balls in the backpack this morning.', 'Some were used, and now there are 16 left.'],
        question: 'How many balls were used?',
        steps: [ { label: 'Solve it', answer: 12 } ] },
      { id: 'ku-5', title: 'Trading Cards', hero: 'sparkmouse', unit: 'cards',
        lines: ['Your uncle gave you 50 trading cards for your birthday.', 'You gave 8 to your best friend and 6 to your cousin.'],
        question: 'How many trading cards do you have left?',
        steps: [ { label: 'Solve it', answer: 36 } ] },
      { id: 'ku-6', title: 'Emerald Split', hero: 'miner', unit: 'per pouch',
        lines: ['A miner finds 96 emeralds in a temple.', 'She shares them equally between 8 pouches.'],
        question: 'How many emeralds go in each pouch?',
        steps: [ { label: 'Solve it', answer: 12 } ] },
      { id: 'ku-7', title: 'Loop Laps', hero: 'speedster', unit: 'seconds',
        lines: ['Dash runs one loop in 7 seconds.', 'He runs 9 loops without stopping.'],
        question: 'How many seconds did all 9 loops take?',
        steps: [ { label: 'Solve it', answer: 63 } ] },
      { id: 'ku-8', title: 'Rooftop Count', hero: 'webhero', unit: 'rooftops',
        lines: ['Web checks 125 rooftops on Saturday.', 'On Sunday he checks 87 rooftops.'],
        question: 'How many rooftops did he check in all?',
        steps: [ { label: 'Solve it', answer: 212 } ] }
    ]
  }
};

export function wordSetKeys() { return Object.keys(WORD_SETS); }
